### ISSUE TITLE
JUnit plugin requires Jenkins 2.321

### ISSUE THREAD

**Issue by tuomastielinen** [PacktPublishing/Practical-Jenkins-2.x#3]
In chapter 3 JUnit plugin is needed. But at this time in the book Jenkins is still in version 2.263.1 and plugin needs version 2.321.

https://plugins.jenkins.io/junit/

**Comment by calvinpark** [comment]
Hi Tuomas, as new plugins get released, the version numbers of the plugins will change from what's in the book. Were you abel to resolve the issue? Happy to help if you need any. Thanks

**Comment by tuomastielinen** [comment]
Hi, I didn't realize that the JUnit plugin was already installed. That's why I had trouble finding it under available plugins.

Sorry for false alarm.

I'm enjoying your book otherwise 😄.

**Comment by calvinpark** [comment]
Ah cool. That in fact confused the reviewers of the book a few times - I'll be sure to call it out in the next revision. Happy to hear that you like the book :)
